import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useEditorStore } from '@/state/useEditorStore';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft, Sparkles, FileText, Loader2, Zap, CheckCircle, Copy } from 'lucide-react';
import { toast } from 'sonner';

const TEMPLATES = [
  { id: 'blog', label: 'Blog Post Intro', prompt: 'Write an engaging introduction about ' },
  { id: 'social', label: 'Social Media Caption', prompt: 'Write a catchy caption about ' },
  { id: 'email', label: 'Email Body', prompt: 'Write a professional email about ' },
  { id: 'product', label: 'Product Description', prompt: 'Write a product description for ' },
];

export default function ContentGeneratorPage() {
  const navigate = useNavigate();
  const { contentRef } = useEditorStore();
  const [idea, setIdea] = useState('');
  const [template, setTemplate] = useState<string | null>('blog');
  const [output, setOutput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = () => {
    if (!idea.trim()) {
      toast.error('Please enter a topic or idea');
      return;
    }
    const baseTemplate = TEMPLATES.find((t) => t.id === template) || TEMPLATES[0];
    setIsGenerating(true);
    setOutput('');

    setTimeout(() => {
      const text = `${baseTemplate.prompt}${idea}.

This is demo content generated by the AI Content Generator. In a real integration, this would come from your AI backend and follow your exact instructions and tone.`;
      setOutput(text);
      setIsGenerating(false);
      toast.success('Content generated (demo)');
    }, 1200);
  };

  const handleApplyToDoc = () => {
    if (!output) return;
    if (contentRef?.current) {
      contentRef.current.innerText = output;
      toast.success('Generated content applied to document');
      navigate('/');
    }
  };

  const handleCopy = () => {
    if (!output) return;
    navigator.clipboard.writeText(output);
    toast.success('Generated content copied');
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-6">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => navigate('/')}
              className="gap-2"
            >
              <ArrowLeft className="h-4 w-4" />
              Back to Editor
            </Button>
            <div>
              <h1 className="text-2xl font-bold flex items-center gap-2">
                <Sparkles className="h-6 w-6 text-primary" />
                AI Content Generator
              </h1>
              <p className="text-muted-foreground text-sm">Generate demo content from a topic or idea</p>
            </div>
          </div>
          <Badge variant="default" className="gap-1">
            <Zap className="h-3 w-3" />
            Live
          </Badge>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Input</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-2">
                {TEMPLATES.map((t) => (
                  <Button
                    key={t.id}
                    variant={template === t.id ? 'default' : 'outline'}
                    size="sm"
                    className="justify-start"
                    onClick={() => setTemplate(t.id)}
                  >
                    {t.label}
                  </Button>
                ))}
              </div>
              <Textarea
                value={idea}
                onChange={(e) => setIdea(e.target.value)}
                placeholder="Describe what you want to generate... (e.g. a blog about AI tools)"
                className="min-h-[180px] resize-none"
              />
              <div className="flex justify-end">
                <Button onClick={handleGenerate} disabled={isGenerating || !idea.trim()} className="gap-2">
                  {isGenerating ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-4 w-4" />
                      Generate
                    </>
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5" />
                Output
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="min-h-[220px] rounded-md border bg-muted/40 p-3 text-sm whitespace-pre-wrap">
                {output || <span className="text-muted-foreground">Generated content will appear here...</span>}
              </div>
              <div className="flex gap-2 mt-4">
                <Button variant="outline" size="sm" onClick={handleCopy} disabled={!output} className="gap-2">
                  <Copy className="h-4 w-4" />
                  Copy
                </Button>
                <Button size="sm" onClick={handleApplyToDoc} disabled={!output} className="gap-2">
                  <CheckCircle className="h-4 w-4" />
                  Apply to Document
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
